#!/bin/bash
# Stashes and updates all the Cinnamon-relevant things to the latest head version

. buildorder

for dir in ${BUILDORDER[@]}; do
    echo "..............Running git pull for $dir upstream master"
    cd $dir
    git clean -xfd
    git reset --hard HEAD
    git checkout master
    git pull
    cd ..
done
